#pragma once

#include <cstdint>
#include <string_view>

namespace dualpad::input::backend
{
    enum class NativeControlCode : std::uint32_t
    {
        None = 0,
        Jump,
        Activate,
        ReadyWeapon,
        TweenMenu,
        Sprint,
        Sneak,
        Shout,
        FavoritesCombo,
        Hotkey1,
        Hotkey2,
        Hotkey3,
        Hotkey4,
        Hotkey5,
        Hotkey6,
        Hotkey7,
        Hotkey8,
        TogglePOV,

        Wait,
        Journal,
        Pause,
        NativeScreenshot,

        MenuConfirm,
        MenuCancel,
        MenuScrollUp,
        MenuScrollDown,
        MenuLeft,
        MenuRight,
        MenuDownloadAll,
        MenuPageUp,
        MenuPageDown,
        MenuSortByName,
        MenuSortByValue,

        DialoguePreviousOption,
        DialogueNextOption,

        FavoritesPreviousItem,
        FavoritesNextItem,
        FavoritesAccept,
        FavoritesCancel,
        FavoritesUp,
        FavoritesDown,

        ConsoleExecute,
        ConsoleHistoryUp,
        ConsoleHistoryDown,
        ConsolePickPrevious,
        ConsolePickNext,
        ConsoleNextFocus,
        ConsolePreviousFocus,

        ItemZoom,
        ItemXButton,
        ItemYButton,
        InventoryChargeItem,

        BookClose,
        BookPreviousPage,
        BookNextPage,

        MapCancel,
        MapClick,
        MapOpenJournal,
        MapPlayerPosition,
        MapLocalMap,

        CursorClick,
        JournalXButton,
        JournalYButton,

        DebugOverlayNextFocus,
        DebugOverlayPreviousFocus,
        DebugOverlayUp,
        DebugOverlayDown,
        DebugOverlayLeft,
        DebugOverlayRight,
        DebugOverlayToggleMinimize,
        DebugOverlayToggleMove,
        DebugOverlayB,
        DebugOverlayY,
        DebugOverlayX,
        TFCWorldZUp,
        TFCWorldZDown,
        TFCLockToZPlane,
        LockpickingDebugMode,
        LockpickingCancel,
        CreationsAccept,
        CreationsCancel,
        CreationsUp,
        CreationsDown,
        CreationsLeft,
        CreationsRight,
        CreationsOptions,
        CreationsLoadOrderAndDelete,
        CreationsLikeUnlike,
        CreationsSearchEdit,
        CreationsPurchaseCredits,
        FavorCancel,

        MoveStick,
        LookStick,
        MenuStick,
        FavoritesLeftStick,
        ItemLeftEquipTrigger,
        ItemRightEquipTrigger,
        ItemRotateStick,
        MapLookStick,
        MapZoomOutTrigger,
        MapZoomInTrigger,
        MapCursorStick,
        StatsRotateStick,
        CursorMoveStick,
        JournalTabLeftTrigger,
        JournalTabRightTrigger,
        DebugOverlayLeftTrigger,
        DebugOverlayRightTrigger,
        TFCCameraZDownTrigger,
        TFCCameraZUpTrigger,
        DebugMapLookStick,
        DebugMapZoomOutTrigger,
        DebugMapZoomInTrigger,
        DebugMapMoveStick,
        LockpickingRotatePickStick,
        LockpickingRotateLockStick,
        CreationsLeftStick,
        CreationsCategorySideBarTrigger,
        CreationsFilterTrigger,
        LeftTriggerAxis,
        RightTriggerAxis
    };

    std::string_view ToString(NativeControlCode code);
}
